# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-26 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='productImages')),
                ('type', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('collar', models.CharField(max_length=10)),
                ('material', models.CharField(max_length=15)),
            ],
        ),
    ]
